source 'https://rubygems.org'

# gem 'bcrypt-ruby', '~> 3.0.0'
gem 'acts_as_list'
gem 'coffee-rails', '~> 4.0.0'
gem 'capybara'
gem 'capybara-webkit'
gem 'selenium-webdriver'
gem 'database_cleaner'
gem 'factory_girl_rails'
gem 'font-awesome-rails'
gem 'haml-rails'
gem 'hogan_assets'
gem 'jasmine'
gem 'jbuilder', '~> 1.2'
gem 'jquery-rails'
gem 'jquery-ui-rails'
gem 'launchy'
gem 'pg'
gem 'pry'
gem 'inherited_resources'
gem 'rails', '4.0.0'
gem 'rails-backbone'
gem 'rspec-rails'
gem 'sass-rails', '~> 4.0.0'
gem 'simple_form'
gem 'shoulda-matchers'
gem 'turbolinks'
gem 'uglifier', '>= 1.3.0'
gem 'foundation-rails'
# gem 'unicorn'

group :doc do
  gem 'sdoc', require: false
end
